version: "3.9"

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ecommerce-backend

    ports:
      - "8081:8081"

    env_file:
      - app/.env

    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ecommerce-frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend

    restart: unless-stopped