spring.application.name=app
#  ============= server port ====================
server.port = 8081
# ============== database connection ============
spring.datasource.url = jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username = postgres
spring.datasource.password = Yashwanth@13

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql = true
spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect


# ================== secret token =============
app.security.secret.key = r9cYl1Vi13n9spcXjbKZdNruThoNMwXIRhMfuMy4Mp6

# ================= EXPIRATION TIME ==================
app.security.secret.key.expiration = 86400000

# spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
# spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

# spring.security.oauth2.client.registration.google.scope=email,profile

# spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB